### ISSUE TITLE
Why both forward and backward inference are needed when using dbn to generate hidden features?

### ISSUE THREAD

**Issue by zhujiangang** [wuaalb/keras_extensions#8]
Hi, I am a newer on rbm and dbn and I am reading your code about rbm and dbn implementation on keras. I feel confused that why both forward and backward inference are needed when using dbn to generate hidden features. Why not only 'forward'? Would you please explain this to me? Thank you!

**Comment by wuaalb** [comment]
It depends on what you want to do.
If you want to do classification you probably only need observed to hidden and stick a classifier on top; for other tasks you may want to go from hidden to observed.
